### ISSUE TITLE
incorrect compare

### ISSUE THREAD

**Issue by vah13** [lvc/pkgdiff#18]
hi. I have 2 java file, 
in first file have 
JCO.Repository("Hell1", connClient);

in second file 
JCO.Repository("Hell2", connClient);

but where I was compared pkgdiff don't show change.

**Comment by lvc** [comment]
Hello,

Seems that you are trying to compare implementations of your methods. The tool checks for changes in declarations of public methods only. Try to change the number of parameters or type of a parameter and you'll see detected changes.

Thanks for reporting the issue.
