### ISSUE TITLE
pkgdiff is not able to execute abi-compliance-checker correctly

### ISSUE THREAD

**Issue by hobbes1069** [lvc/pkgdiff#20]
I have a user trying pkgdiff 1.7.0 but abi-compliance-checker (1.99.13) seems to not like the options being passed to it.

https://bugzilla.redhat.com/show_bug.cgi?id=1277606

**Comment by lvc** [comment]
The issue is that the abi-cc tool can only take arguments with suffixes "abi", "abidump" and "dump". But pkgdiff passes "*.txt" files to it. I'll fix this soon.

Thank you.

**Comment by hobbes1069** [comment]
Any updates on this issue?

**Comment by aponomarenko** [comment]
Fixed in 1.7.1.

Thank you.
