### ISSUE TITLE
use `file` command to determine filetype

### ISSUE THREAD

**Issue by seanjensengrey** [lvc/pkgdiff#23]
It would be nice to use the `file` command to determine the type of the pkg being compared rather than extension.

The use case I hit is

1. wget \<url to package\>
2. wget \<url to same package, different url\>

Both had the same name but different sizes, but the second one now ends in .1 `pkgdiff` complains that it doesn't understand `.1` format. When `file` reports `Zip archive data, at least v2.0 to extract`

**Comment by lvc** [comment]
Hello,

The issue has been fixed by the commit 0ebfd8eb21c663744072ef9599fd97aea033daf7.

Thank you.
