### ISSUE TITLE
master is broken

### ISSUE THREAD

**Issue by heftig** [lvc/pkgdiff#25]
The current `master` produces lots of `sh` syntax errors. I think it's this change:

```diff
-    system($Cmd." >\"".$SPath."\" 2>$TMP_DIR/null");
+    
+    my $TmpFile = $TMP_DIR."/null";
+    qx/$Cmd." >\"".$SPath."\" 2>$TmpFile/;
```

Since `qx/…/` is a command literal, using `.` to concatenate inside it is nonsense. I think it should be:
```perl
qx/$Cmd >"$SPath" 2>"$TmpFile"/;
```

**Comment by lvc** [comment]
Hi,

The code is fixed.

Thanks a lot!
