### ISSUE TITLE
[Question] pkgdiff for comparing jars

### ISSUE THREAD

**Issue by debraj-manna** [lvc/pkgdiff#33]
Can `pkgdiff` be used for comparing jars? I am asking this as https://lvc.github.io/pkgdiff/ does not mention anything about jars. 

If yes how does it compare jars? I am asking this as to test `pkgdiff` I created a dummy jar with some java files and then added some comments in one of the java file and then created the jar again. `pkgdiff` correctly recognized this and reported the jars as unchanged. What all things are checked to determine the jars are different ?

**Comment by lvc** [comment]
Hi,

The tool shows differences at byte-code level. It's just a visual diff of `javap` output for old and new archive versions.

For better detailed analysis of changes in jars please use https://github.com/lvc/japi-compliance-checker.

Thank you.

**Comment by debraj-manna** [comment]
Thanks @lvc  for replying.

Couple of more queries -

1. Are we passing any flag to `javap` ?
2. I have a zip file which has some jars inside it. To test this I modified a java file and recreated one of the jar and then the zip file. On running `pkgdiff` on the two zips it correctly identified the jar having the changes. So in case of this use case is `pkgdiff` passing the zips to `javap` or it is unzipping and then running javap on all pair of jars.

For my use case pkgdiff I feel `pkgdiff` will be more suitable as I just need to know if something is changed in the jar (not detailed analysis) also as per the [doc](https://lvc.github.io/pkgdiff/) this can also be used for comparing other formats  like tar,zip, etc.

**Comment by lvc** [comment]
> is pkgdiff passing the zips to javap or it is unzipping and then running javap on all pair of jars

pkgdiff extracts classes from jars and then diffs their javap outputs.
