### ISSUE TITLE
Visual Diff reports are empty

### ISSUE THREAD

**Issue by kranthim84** [lvc/pkgdiff#39]
hi,
I am using 1.8 version  and I am trying to compare jar files with the following options
 -check-byte-code -full-method-diffs

The main report shows the % change in the changed Java Classes. However, if I click on the link "diff" , it redirects me to a blank page. 
The HTML files are created for each of the Changed classes but they are empty.

Can you please advise what could be the reason?

BTW, I get a following warning when I run the tool
WARNING: perl-File-LibMagic is not installed
I think, this should not be the reason for the empty reports.

Please help.

**Comment by kranthim84** [comment]
I have figured out the reason by adding Debugs in rfcdiff shell script.

Reason: The awk version is I was using is not compatible with rfcdiff. I had to install GNU Awk to make the class level diff reports working.

**Comment by hobbes1069** [comment]
Although you closed this, I'm wondering if it's worth doing some version checking so a helpful error message would be generated instead of unexpected behavior.

**Comment by Yunme** [comment]
On MacOS, Install `gawk` use `brew install gawk`.

**Comment by mseri** [comment]
Installing gawk is not solving the issue for me :(
